name: Flutter Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Windows Release
      run: flutter build windows --release
    
    # Opción 1: Subir desde la ruta correcta (x64)
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: build/windows/x64/runner/Release/
        
    # Opción 2: Alternativa - Subir toda la carpeta de build si quieres incluir todo
    # - name: Upload Windows Build (Complete)
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: windows-release-complete
    #     path: build/windows/x64/runner/
        
    # Opción 3: Para debugging - Ver qué archivos se generaron
    - name: List build contents (for debugging)
      if: always()
      run: |
        echo "Contents of build/windows:"
        dir build\windows\ /s /b
      shell: cmd
