name: Flutter Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # OPCIÓN 1: Usar el canal stable (RECOMENDADO)
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'  # Solo especifica el canal
        # NO uses flutter-version cuando especificas channel
    
    # OPCIÓN 2: Si prefieres una versión específica de Flutter
    # - name: Setup Flutter (Versión específica)
    #   uses: subosito/flutter-action@v2
    #   with:
    #     flutter-version: '3.19.0'  # Especifica una versión exacta
    #     # NO uses channel cuando especificas flutter-version
    
    - name: Check Flutter version
      run: flutter --version
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Windows Release
      run: flutter build windows --release
    
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: build/windows/x64/runner/Release/
        if-no-files-found: error  # Falla si no encuentra archivos
    
    # Opcional: Para debugging
    - name: List build contents (debugging)
      if: failure()  # Solo se ejecuta si falla algo
      run: |
        echo "=== Checking build directory structure ==="
        if (Test-Path "build\windows") {
          Get-ChildItem -Path "build\windows" -Recurse | Select-Object FullName
        } else {
          echo "build\windows directory does not exist"
        }
      shell: powershell
